### PR TITLE
Test non-sticky extra LGTM check

### PR DESCRIPTION
**Pull request by sauron-demo-Calvin**
Testing non-sticky extra LGTM check

http://localhost:8000/sauron-demo/sauron-demo-auto-yren-zenefits-1476315443/pull/1394

### CODE REVIEW

**Comment by sauron-demo-Josephine** [comment]
LGTM

**Comment by sauron-demo-bbao** [comment]
#!merge

**Comment by sauron-demo-bbao** [comment]
QA-LGTM

**Comment by sauron-demo-bbao** [comment]
QA-LGTM AT e84eac404ab22048448491f38a2f7ee4230a586e

**Pull request closed without merging**
